### ISSUE TITLE
need SPI in kernel or as module

### ISSUE THREAD

**Issue by tve** [NextThingCo/CHIP-linux#52]
IMHO the kernel should support SPI, including the patch for transfer sizes over 63 bytes and inclusion in the DTB (or a working overlay). See https://patchwork.kernel.org/patch/5726181/ and http://www.chip-community.org/index.php/Kernel_4.4_with_SPI_and_1-wire for a DTS patch. Thanks!

**Comment by mripard** [comment]
That patch has already been applied: https://github.com/NextThingCo/CHIP-linux/commit/384022b8d2472de7bce06a06feb555fc92d44391

And we can't enable the SPI by default, since those pins have other uses too (like MMC), that people might rely one. You have an overlay here though: https://github.com/NextThingCo/CHIP-dt-overlays/blob/master/samples/sample-spi.dts
